version: '3.8'

services:
  chainlink:
    build: .
    container_name: chainlink
    ports:
      - '6688:6688'
    command: node -config /chainlink/config.toml -secrets /chainlink/secrets.toml start
    depends_on:
      - postgres
      - hardhat-node

  hardhat-node:
    image: node:18-alpine
    container_name: hardhat-node
    ports:
      - '8545:8545'
    command: |
      sh -c '
        mkdir /app &&
        cd /app &&
        npm init -y &&
        npm install hardhat &&
        echo "module.exports = {solidity: \"0.8.4\"};" > hardhat.config.js &&
        npx hardhat node
      '

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: chainlink
      POSTGRES_PASSWORD: a1b2c3d4e5f6g7h8i9
      POSTGRES_DB: chainlink
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: