import { Lato } from "next/font/google";
import { Layout } from "src/components/layout";
import AppProvider from "src/providers/app/provider";

const font = Lato({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <AppProvider>
          <Layout headerProps={{}} footerProps={{}}>
            {children}
          </Layout>
        </AppProvider>
      </body>
    </html>
  );
}
